/* Δημιουργία Πίνακα {ΣΧΟΛΙΟ} */

CREATE TABLE COMMENTS(
    COMMENTID INT PRIMARY KEY,
    SYG_MHNYMATOS VARCHAR(30) NOT NULL,
    KOD MHNYMATOS INT NOT NULL,
    KOD SXOLIOU INT NOT NULL,
    SUGGRAFEAS_SXOLIOU VARCHAR(30) NOT NULL,
    KEIMENO SXOLIOU VARCHAR(4000) NOT NULL,
    HMEROMHNIA DATE NOT NULL,
    CHECK (KOD MHNYMATOS > 0), 
    CHECK (KOD SXOLIOU > 0)
);