/* Δημιουργία Πίνακα {ΑΡΕΣΕΙ} */

CREATE TABLE LIKES (
    LIKEID INT PRIMARY KEY,
    ONOMAXEIRISTH VARCHAR(30) NOT NULL,
    SYG MHNYMATOS VARCHAR (30) NOT NULL,
    KOD MHNYMATOS INT NOT NULL,
    CHECK (KOD MHNYMATOS > 0)
);