-- DROP DATABASE IF EXISTS assignment1;

/* Δημιουργία Πίνακα {ΧΡΗΣΤΗΣ} */
DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS (
    ONOMAXEIRISTH VARCHAR(30) NOT NULL,
    ONOMA VARCHAR (60) NOT NULL,
    EPONYMO VARCHAR(120),
    GENOS VARCHAR (20) NOT NULL,
    POLH VARCHAR(60),
    XORA VARCHAR (60) NOT NULL,
	PRIMARY KEY(ONOMAXEIRISTH)
);

/* Δημιουργία Πίνακα {ΜΗΝΥΜΑ} */
DROP TABLE IF EXISTS MESSAGES CASCADE;
CREATE TABLE MESSAGES (
    SYG_MHNYMATOS VARCHAR(30) NOT NULL,
    KOD_MHNYMATOS INT NOT NULL,
    IDIOKTHTHS_TOIXOY VARCHAR (30) NOT NULL,
    PERIEXOMENO VARCHAR (4000) NOT NULL,
    HMEROMHNIA DATE NOT NULL,
    CHECK (KOD_MHNYMATOS > 0),
	PRIMARY KEY(KOD_MHNYMATOS),
    FOREIGN KEY(IDIOKTHTHS_TOIXOY) REFERENCES USERS (ONOMAXEIRISTH) ON DELETE CASCADE
);

/* Δημιουργία Πίνακα {ΣΧΟΛΙΟ} */
DROP TABLE IF EXISTS COMENTS CASCADE;
CREATE TABLE COMENTS(
    SYG_MHNYMATOS VARCHAR(30) NOT NULL,
    KOD_MHNYMATOS INT NOT NULL,
    KOD_SXOLIOU INT NOT NULL,
    SUGGRAFEAS_SXOLIOU VARCHAR(30) NOT NULL,
    KEIMENO_SXOLIOU VARCHAR(4000) NOT NULL,
    HMEROMHNIA DATE NOT NULL,
    CHECK (KOD_MHNYMATOS > 0),
    CHECK (KOD_SXOLIOU > 0),
	PRIMARY KEY(KOD_SXOLIOU),
    FOREIGN KEY(KOD_MHNYMATOS) REFERENCES MESSAGES (KOD_MHNYMATOS) ON DELETE CASCADE,
	FOREIGN KEY(SUGGRAFEAS_SXOLIOU) REFERENCES USERS (ONOMAXEIRISTH) ON DELETE CASCADE
);


/* Δημιουργία Πίνακα {ΑΡΕΣΕΙ} */
DROP TABLE IF EXISTS LIKES CASCADE;
CREATE TABLE LIKES (
    ONOMAXEIRISTH VARCHAR(30) NOT NULL,
    SYG_MHNYMATOS VARCHAR (30) NOT NULL,
    KOD_MHNYMATOS INT NOT NULL,
    CHECK (KOD_MHNYMATOS > 0),
	PRIMARY KEY(ONOMAXEIRISTH, KOD_MHNYMATOS),
    FOREIGN KEY(ONOMAXEIRISTH) REFERENCES USERS (ONOMAXEIRISTH) ON DELETE CASCADE,
    FOREIGN KEY(KOD_MHNYMATOS) REFERENCES MESSAGES (KOD_MHNYMATOS) ON DELETE CASCADE
);