/* Δημιουργία Πίνακα {ΧΡΗΣΤΗΣ} */

CREATE TABLE USERS (
    ONOMAXEIRISTH VARCHAR(30) NOT NULL,
    ONOMA VARCHAR (60) NOT NULL,
    EPONYMO VARCHAR(120),
    GENOS VARCHAR (20) NOT NULL,
    POLH VARCHAR(60),
    XORA VARCHAR (60) NOT NULL
);

/* Δημιουργία Πίνακα {ΜΗΝΥΜΑ} */

CREATE TABLE MESSAGES (
    SYG_MHNYMATOS VARCHAR(30) NOT NULL,
    KOD_MHNYMATOS INT NOT NULL,
    IDIOKTHTHS TOIXOY VARCHAR (30) NOT NULL,
    PERIEXOMENO VARCHAR (4000) NOT NULL,
    HMEROMHNIA DATE NOT NULL,
    CHECK (KOD MHNYMATOS > 0)
);

/* Δημιουργία Πίνακα {ΣΧΟΛΙΟ} */

CREATE TABLE COMENTS(
    SYG_MHNYMATOS VARCHAR(30) NOT NULL,
    KOD MHNYMATOS INT NOT NULL,
    KOD SXOLIOU INT NOT NULL,
    SUGGRAFEAS_SXOLIOU VARCHAR(30) NOT NULL,
    KEIMENO SXOLIOU VARCHAR(4000) NOT NULL,
    HMEROMHNIA DATE NOT NULL,
    CHECK (KOD MHNYMATOS > 0), 
    CHECK (KOD SXOLIOU > 0)
);

/* Δημιουργία Πίνακα {ΑΡΕΣΕΙ} */
CREATE TABLE LIKES (
    ONOMAXEIRISTH VARCHAR(30) NOT NULL,
    SYG MHNYMATOS VARCHAR (30) NOT NULL,
    KOD MHNYMATOS INT NOT NULL,
    CHECK (KOD MHNYMATOS > 0)
);